#manifest
self as ui_common.constants

#defs
// GlobalZIndex
$ZINDEX_LOADSCREEN = 10
$ZINDEX_MAKE_LOBBY_POPUP = 13
$ZINDEX_JOIN_LOBBY_POPUP = 14
$ZINDEX_ACK_LOBBY_POPUP = 15
$ZINDEX_RECONNECTING_OVERLAY = 20
